=== estiljr/Taiwan_Development/MP2/mp2/toolbox/JE/ISIS2DXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML schema for ISIS 2D control file, copyright Halcrow Group ltd, 2009-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.halcrow.com/ISIS2D" targetNamespace="http://www.halcrow.com/ISIS2D" elementFormDefault="qualified">
	<xs:element name="ISIS2Dproject">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="link1d" type="link1dType" minOccurs="0"/>
				<xs:element name="logfile" type="xs:string" minOccurs="0"/>
				<xs:element name="domain" type="domainType" maxOccurs="unbounded"/>
				<xs:element name="restart_options" type="restart_optionsType" minOccurs="0"/>
				<xs:element name="advanced_options" type="advanced_optionsType" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="checkType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="on"/>
			<xs:enumeration value="off"/>
			<xs:enumeration value="true"/>
			<xs:enumeration value="false"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="run_scheme">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ADI"/>
			<xs:enumeration value="TVD"/>
			<xs:enumeration value="FAST"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="wet_boundaryType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="warning"/>
			<xs:enumeration value="error"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="double_precisionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="advised"/>
			<xs:enumeration value="required"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="roughness_law">
		<xs:restriction base="xs:string">
			<xs:enumeration value="manning"/>
			<xs:enumeration value="chezy"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="roughness_distribution_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="global"/>
			<xs:enumeration value="file"/>
			<xs:enumeration value="mastermap"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="initial_condition_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="globalwaterlevel"/>
			<xs:enumeration value="globaldepth"/>
			<xs:enumeration value="elevationfile"/>
			<xs:enumeration value="depthfile"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="time_units">
		<xs:restriction base="xs:string">
			<xs:enumeration value="day"/>
			<xs:enumeration value="hour"/>
			<xs:enumeration value="minute"/>
			<xs:enumeration value="second"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="rainfall_units">
		<xs:restriction base="xs:string">
			<xs:enumeration value="mm/hr"/>
			<xs:enumeration value="mm/h"/>
			<xs:enumeration value="m/s"/>
			<xs:enumeration value="in/hr"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="boundary_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="waterelevation"/>
			<xs:enumeration value="totalflow"/>
			<xs:enumeration value="flowperunitwidth"/>
			<xs:enumeration value="verticalflow"/>
			<xs:enumeration value="verticalflowperunitwidth"/>
			<xs:enumeration value="elevation"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="output_format">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SMS9"/>
			<xs:enumeration value="CSV"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="output_variable">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Flow"/>
			<xs:enumeration value="Elevation"/>
			<xs:enumeration value="Velocity"/>
			<xs:enumeration value="Depth"/>
			<xs:enumeration value="Froude"/>
			<xs:enumeration value="Hazard"/>
			<xs:enumeration value="Bedelevation"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="output_variables">
		<xs:list itemType="output_variable"/>
	</xs:simpleType>
	<xs:simpleType name="boundary_value_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="timevar"/>
			<xs:enumeration value="fixedvalue"/>
			<xs:enumeration value="ied"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="computational_areaType">
		<xs:sequence>
			<xs:element name="xll" type="xs:double"/>
			<xs:element name="yll" type="xs:double"/>
			<xs:element name="dx" type="xs:double"/>
			<xs:element name="nrows" type="xs:integer"/>
			<xs:element name="ncols" type="xs:integer"/>
			<xs:element name="active_area" type="xs:string" minOccurs="0"/>
			<xs:element name="rotation" type="xs:double" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="timeType">
		<xs:sequence>
			<xs:element name="start_time" type="xs:time" minOccurs="0"/>
			<xs:element name="start_date" type="xs:string" minOccurs="0"/>
			<xs:element name="total">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="unit" type="time_units"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="restart_optionsType">
		<xs:sequence>
			<xs:element name="read" type="xs:string" minOccurs="0"/>
			<xs:element name="single" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="unit" type="time_units"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="series" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="unit" type="time_units"/>
							<xs:attribute name="start" type="xs:double"/>
							<xs:attribute name="count" type="xs:integer"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="run_dataType">
		<xs:sequence>
			<xs:element name="time_step" type="xs:double"/>
			<xs:element name="scheme" type="run_scheme"/>
			<xs:element name="double_precision" type="double_precisionType" minOccurs="0"/>
			<xs:element name="beta" type="xs:double" minOccurs="0"/>
			<xs:element name="eddyviscosity" type="xs:double" minOccurs="0"/>
			<xs:element name="wall" type="xs:string" minOccurs="0"/>
			<xs:element name="upwind" type="xs:string" minOccurs="0"/>
			<xs:element name="flddry" type="xs:string" minOccurs="0"/>
			<xs:element name="nadvit" type="xs:integer" minOccurs="0"/>
			<xs:element name="drydepth" type="xs:double" minOccurs="0"/>
			<xs:element name="fricdepth" type="xs:double" minOccurs="0"/>
			<xs:element name="calcdepth" type="xs:double" minOccurs="0"/>
			<xs:element name="merge" type="xs:double" minOccurs="0"/>
			<xs:element name="disc" type="xs:double" minOccurs="0"/>
			<xs:element name="filter" type="xs:double" minOccurs="0"/>
			<xs:element name="preprocess_fast" type="xs:string" minOccurs="0"/>
			<xs:element name="pathMarkup_fast" type="xs:string" minOccurs="0"/>
			<xs:element name="pathDepth_fast" type="xs:double" minOccurs="0"/>
      <xs:element name="pathWidth_fast" type="xs:double" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="boundary_conditionsType">
		<xs:sequence>
			<xs:element name="boundary" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="BC" type="boundary_type"/>
						<xs:element name="file" type="xs:string" minOccurs="0"/>
						<xs:element name="xy" type="xs:string" minOccurs="0"/>
						<xs:element name="value">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="type" type="boundary_value_type" use="required"/>
										<xs:attribute name="time_units" type="time_units" use="optional"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="hydrologyType">
		<xs:sequence>
			<xs:element name="source" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="file" type="xs:string"/>
						<xs:element name="value">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="time_units" type="time_units"/>
										<xs:attribute name="units" type="rainfall_units" use="optional"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="output_resultsType">
		<xs:sequence>
			<xs:element name="hazard_debris_factor_method" minOccurs="0">
				<xs:complexType>
					<xs:choice>
						<!-- either one or the other of these -->
						<xs:element name="static">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="factor" type="xs:float" use="required"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="varying">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="land_use" type="land_use_type" use="required"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="output" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="variables" type="output_variables"/>
						<xs:element name="frequency" type="xs:double"/>
						<xs:element name="xy" type="xs:string" minOccurs="0"/>
					</xs:sequence>
					<xs:attribute name="expand" type="xs:integer"/>
					<xs:attribute name="output_id" type="xs:string" use="optional"/>
					<xs:attribute name="format" type="output_format" use="required"/>
					<xs:attribute name="output_after" type="xs:double" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="flowline" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="frequency" type="xs:float" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="massfile" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="frequency" type="xs:float" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="check" type="checkType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="max_intvl" type="xs:integer" use="optional"/>
	</xs:complexType>
	<xs:complexType name="link1dType">
		<xs:sequence>
			<xs:element name="link" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="domain" type="xs:string" use="optional"/>
							<xs:attribute name="weircd" type="xs:double" use="optional"/>
							<xs:attribute name="weirml" type="xs:double" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="ief" type="xs:string"/>
			<xs:element name="mb">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="frequency" type="xs:double" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="weircd" type="xs:double" use="optional"/>
		<xs:attribute name="weirml" type="xs:double" use="optional"/>
	</xs:complexType>
	<xs:complexType name="domainType">
		<xs:sequence>
			<xs:element name="computational_area" type="computational_areaType" minOccurs="0"/>
			<xs:element name="topography" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="time" type="timeType"/>
			<xs:element name="run_data" type="run_dataType"/>
			<xs:element name="initial_conditions" type="initial_conditionsType" minOccurs="0"/>
			<xs:element name="roughness" type="roughnessType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="boundary_conditions" type="boundary_conditionsType" minOccurs="0"/>
			<xs:element name="hydrology" type="hydrologyType" minOccurs="0"/>
			<xs:element name="output_results" type="output_resultsType"/>
		</xs:sequence>
		<xs:attribute name="domain_id" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="advanced_optionsType">
		<xs:sequence>
			<xs:element name="number_of_threads" type="xs:positiveInteger" minOccurs="0"/>
			<xs:element name="debug_memory_alignment" type="xs:string" minOccurs="0"/>
			<xs:element name="benchmarking" type="xs:string" minOccurs="0"/>
			<xs:element name="wet_boundary" type="wet_boundaryType" minOccurs="0"/>
			<xs:element name="flag_mass_error" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="check_after_seconds" type="xs:integer" use="required"/>
							<xs:attribute name="tolerance_pct" type="xs:float" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="correct_negative_depths" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="roughnessType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="law" type="roughness_law" use="required"/>
				<xs:attribute name="type" type="roughness_distribution_type" use="required"/>
				<xs:attribute name="default_roughness" type="xs:double" use="optional"/>
				<xs:attribute name="lookuptable" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="initial_conditionsType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="initial_condition_type" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="land_use_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pasture"/>
			<xs:enumeration value="woodland"/>
			<xs:enumeration value="urban"/>
			<xs:enumeration value="conservative"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== estiljr/Taiwan_Development/MP2/isis/isis2d/test_files/Ha001_Cat0001_Dom010_adi_2_tvd.xml
<ISIS2Dproject xmlns="http://www.halcrow.com/ISIS2D" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.halcrow.com/ISIS2D ISIS2DXMLSchema.xsd" name="SEPA National Fluvial Modelling">
  <domain domain_id="Ha001_Cat0001_Dom010">
    <computational_area>
      <xll>325470.0</xll>
      <yll>935290.0</yll>
      <dx>10.0</dx>
      <nrows>510</nrows>
      <ncols>229</ncols>
      <active_area>GIS\Active_Area.shp</active_area>
    </computational_area>
    <topography>GIS\topo\nd23ne.asc</topography>
    <topography>GIS\topo\nd24se.asc</topography>
    <topography>GIS\Z_Polygons.shp</topography>
    <time>
      <start_time>00:00:00</start_time>
      <start_date>1/1/2000</start_date>
      <total unit="hour">100</total>
    </time>
    <run_data>
      <time_step>5.0</time_step>
      <scheme>TVD</scheme>
    </run_data>
    <initial_conditions type="elevationfile">GIS\iwl.asc</initial_conditions>
    <roughness law="manning" type="global">0.05</roughness>
    <roughness law="manning" type="file">GIS\roughness\nd23ne.asc</roughness>
    <roughness law="manning" type="file">GIS\roughness\nd24se.asc</roughness>
    <roughness law="manning" type="globalmultiplier">1.4</roughness>
    <boundary_conditions>
      <boundary>
        <BC>verticalflow</BC>
        <file>GIS\Main_Inflow_002.shp</file>
        <value type="timevar" time_units="hour">0	0
0.5	3.44287999899
9999	3.44287999899
</value>
      </boundary>
      <boundary>
        <BC>waterelevation</BC>
        <file>GIS\Downstream_Level_001.shp</file>
        <value type="fixedvalue">1.79</value>
      </boundary>
      <boundary>
        <BC>verticalflow</BC>
        <file>GIS\Main_Inflow_001.shp</file>
        <value type="timevar" time_units="hour">0	0
0.5	3.17343796288
9999	3.17343796288
</value>
      </boundary>
    </boundary_conditions>
    <output_results>
      <hazard_debris_factor_method>
        <static factor="0.0"/>
      </hazard_debris_factor_method>
      <output output_id="" format="SMS9">
        <variables>
          Depth
          Elevation
          Velocity
          Hazard
          Froude
        </variables>
        <frequency>3600.0</frequency>
      </output>
      <massfile frequency="60">MB.csv</massfile>
      <check>true</check>
    </output_results>
  </domain>
  <advanced_options>
    <number_of_threads>1</number_of_threads>
    <!-- <wet_boundary>error</wet_boundary> -->
    <flag_mass_error check_after_seconds="14400" tolerance_pct="50000.0"/>
    <!-- BEWARE: check_after_seconds is an INTEGER variable -->
    <stop_on_convergence fail_on_non_convergence="true">
      <!--
            window_size:
                The gap of time at which values are compared at either 
                end, e.g. 60 mins
            
            Averages of domain volume are made at the start and end of 
            the inspection window:
                volStart = AVERAGE(v@t=now, v@t=now-3mins, v@t=now-6mins.... .... v@t=now-12mins) (7 samples)
                volEnd = AVERAGE(v@t=now-1hr, v@t=now-1hr-3mins ... v@t=now-1hr-12mins) (another 7 samples)
            
            The difference in the averaged volumes (vDiff = volEnd - volStart)
            is compared with at least one of three possible criteria:
            
            1) vDiff < volume_comparison_percentage of domain volume
            2) vDiff < total_inflow_comparison_percentage of current total inflow
            3) vDiff < smallest_inflow_comparison_percentage of smallest inflow
            
            If all criteria specified are met - the model is deemed to 
            have converged
            
            minimum_run_time:
                The minimum amount of time to run the model before 
                checking convergence.  Must be larger than window_size
                + 18mins
                
            fail_on_non_convergence:
                If true, model will return an error code when the 
                simulation end time is reached and the model has not 
                converged.  
        -->
      <volume_comparison_percentage>1.0</volume_comparison_percentage>
      <total_inflow_comparison_percentage>1.0</total_inflow_comparison_percentage>
      <smallest_inflow_comparison_percentage>67.0</smallest_inflow_comparison_percentage>
      <minimum_run_time unit="hour">3</minimum_run_time>
      <window_size unit="hour">1</window_size>
    </stop_on_convergence>
  </advanced_options>
</ISIS2Dproject>
